name: Download and install CodecovCLI

on:
  workflow_call:

jobs:
  download_and_install_codecov_cli:
    runs-on: ubuntu-latest
    steps:
      - name: Cache CLI binary
        id: cache-codecov-cli
        uses: actions/cache@v2
        with:
          path: /tmp/codecov
          key: ${{ runner.os }}-codecov-cli
      - name: Download CLI binary
        if: steps.cache-codecov-cli.outputs.cache-hit != 'true'
        run: |
          mkdir /tmp/codecov
          cd /tmp/codecov
          curl --fail -Os https://cli.codecov.io/v0.1.2/linux/codecov
          chmod +x ./codecov
      - name: Get Codecov's GPG
        if: steps.cache-codecov-cli.outputs.cache-hit != 'true'
        run: curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import #
      - name: Get SHAsums
        if: steps.cache-codecov-cli.outputs.cache-hit != 'true'
        run: |
          cd /tmp/codecov
          curl --fail -Os https://cli.codecov.io/v0.1.2/linux/codecov.SHA256SUM
          curl --fail -Os https://cli.codecov.io/v0.1.2/linux/codecov.SHA256SUM.sig   
      - name: Test Signature
        if: steps.cache-codecov-cli.outputs.cache-hit != 'true'
        run: |
          cd /tmp/codecov
          gpgv codecov.SHA256SUM.sig codecov.SHA256SUM
      - name: Test SHAsums
        if: steps.cache-codecov-cli.outputs.cache-hit != 'true'
        run: |
          cd /tmp/codecov
          shasum -a 256 -c codecov.SHA256SUM
      - name: Make binary available to other jobs
        uses: actions/upload-artifact@v2
        with:
          name: codecov-cli-binary
          path: /tmp/codecov/codecov
      